AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "node_modules/**/*"
    - "script/**/*"
    - "support/**/*"
    - "tmp/**/*"
    - "test/**/*"
    - "db/**/"
    - "db/schema.rb"

Style/ConditionalAssignment:
  Enabled: true
Style/StringLiterals:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/WordArray:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/SignalException:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Max: 220
Style/EmptyMethod:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
